version: 1.0.{build}
configuration: Release
before_build:
- nuget restore ".\ThaiBahtText.sln"
build:
  project: .\ThaiBahtText.sln
  verbosity: minimal
artifacts:
- path: GFDN.ThaiBahtText\bin\Release\GreatFriends.ThaiBahtText.dll
  name: DLL File
