version: 1.0.{build}
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: eDQwdQTXfuHz4C9TTshI1oz6nXANBLbHU
before_build:
- nuget restore
build:
  verbosity: minimal
artifacts:
- path: GFDN.ThaiBahtText\bin\Release\GreatFriends.ThaiBahtText.dll
  name: DLL File